In [152]:
 import numpy as np

In [153]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [154]:
b=np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [155]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [156]:
# Create Zeros ,Ones ,Custom array
a=np.zeros((3,3))
print(a)

b=np.ones((2,3))
print(b)

#Array of some constants
c= np.full((3,2),5)
print(c)

#Identity Matrix
d=np.eye(4)
print(d)

#Random Matrix
randomMatrix =np.random.random((2,3))
print(randomMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.31342418 0.69232262 0.87638915]
 [0.89460666 0.08504421 0.03905478]]


In [157]:
print(randomMatrix[:,2])  #Slicing

[0.87638915 0.03905478]


In [158]:
randomMatrix[1,1:]=1
print(randomMatrix)

[[0.31342418 0.69232262 0.87638915]
 [0.89460666 1.         1.        ]]


In [159]:
### Set some rows and columns with any values
z=np.zeros((3,3),dtype=np.int64)  #by default it's float
print(z)
z[1,:]=5
z[:,-1]=7
print(z)


[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [160]:
#Datatypes
print(z.dtype)

int64


In [161]:
#MAthematical Operations

x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

#Element wise Addition/Subtraction
print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [162]:
#Element wise Multiplication/Division
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))
print(np.sqrt(x))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [163]:
# Matrix Multiplication and Dot Products
print(x)
print(y)

print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [164]:
#Multiplication of Vectors => Scalar
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
print(np.dot(a,b))

40


In [165]:
print(a)

[1 2 3 4]


In [166]:
print(sum(a))

10


In [167]:
print(x)

[[1 2]
 [3 4]]


In [168]:
print(np.sum(x))
print(np.sum(x,axis=0))  #axis=0 =>along the column(vertical)   

10
[4 6]


In [169]:
print(np.sum(x,axis=1))    #axis=1  =>along row(horizontal)

[3 7]


In [170]:
#Stacking of array
print(a)
b=b**2
print(b)

[1 2 3 4]
[ 4  9 16 25]


In [171]:
lol=np.stack((a,b),axis=0)  #concatenate both the arrays

In [172]:
print(lol)    

[[ 1  2  3  4]
 [ 4  9 16 25]]


In [173]:
#Reshape a Numpy Array
lol=lol.reshape((8,1))
print(lol)
lol=lol.reshape((8,))
print(lol)
lol=lol.reshape((-1,4))
print(lol)


[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 4]
 [ 9]
 [16]
 [25]]
[ 1  2  3  4  4  9 16 25]
[[ 1  2  3  4]
 [ 4  9 16 25]]


In [212]:
#Important one
a=np.arange(10) 
print(a)
a=np.arange(10)+5
print(a)
check=np.arange(10,step=2)+1
print(check)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
[1 3 5 7 9]


# Numpy Random Module

   - rand : random values in a given shape
   
   - randn : Return a sample from "standard normal" distribution
   
   - randint : Return random integers from low(inclusive) to high (exclusive)
   
   - random_sample:  return random floats in the half-open interval [0.0 , 1.0)
 
   - choice: generates a random sample from a given 1-D array
   
   - Shuffle: shuffles the contents of a sequence
   
   
   

In [183]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

[5 6 9 6 6 6 6 7]


In [184]:
#Return values from a Standard Normal Distribution
a=np.random.randn(2,3)
print(a)

a=np.random.randint(5,10,8)  # 8 random numbers between 5 and 10(exclusive)
print(a)

[[-1.601721   -1.47782957  0.48349585]
 [ 0.18843661 -0.46468632  0.86182712]]
[9 8 9 7 9 7 9 6]


In [185]:
#Randomly Pick one element from a array
element = np.random.choice([1,4,3,2,11,27])
print(element)

4


In [211]:
print(np.random.random_sample((1,5)))
print(3*np.random.random_sample((1,7)) - 6)


[[0.29361415 0.28777534 0.13002857 0.01936696 0.67883553]]
[[-5.36511565 -5.20336002 -4.52528052 -5.83991236 -4.27764718 -5.55981428
  -4.23208339]]


# Some More Numpy Functions - Statistics
- min,max
- mean
- median
- average
- variance
- standard deviation

In [193]:
a=np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))

#Specify axis for the direction in case of multi dimensional array

print(np.min(a,axis=0))
print(np.min(a,axis=1))



[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [194]:
#Mean, average of all the elements

b=np.array([1,2,3,4,5])
m=sum(b)/5
print(m)

print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [199]:
c=np.array([1,5,4,2,0])
print(np.median(c))

#Mean vs Average(it is weighted)
print(np.mean(c))

#Weights
w = np.array([1,2,3,4,5])
print(np.average(c,weights=w)) #(1*1 + 5*2 +4*3 +2*4 + 0*5)/5

#Standard Deviation

#Manual Implementation
u=np.mean(c)
my_std = np.sqrt(np.mean(abs(c-u)**2))
print(my_std)

#inbuilt Function
print(np.std(c))

#Variance
print(my_std**2)  
print(np.var(c))

2.0
2.4
2.066666666666667
1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004


In [201]:
np.linspace(1,10,25)

array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
        4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
        7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
       10.   ])

In [206]:
#Some conditions useful in EDA
val=2

print(c<val) #Prints the boolean indexwise

print(c[c<val]) #Prints the indexes which satisfies the condition

[ True False False False  True]
[1 0]


In [207]:
d=np.ones((2,5),dtype=int)
print(d)

[[1 1 1 1 1]
 [1 1 1 1 1]]
